name: Generate Crawl Artifacts

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  crawl:
    name: crawl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 18
      - run: npm i
      - run: npm start
      - name: "Commit and Push Artifacts"
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: main
          force: true
          directory: outputs/
